name: Publish
on: 
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Wago
        uses: BigWigsMods/packager@v2.3.1
        env:
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
